spring.kafka:
  bootstrap-servers: localhost:9092
  consumer:
    concurrency: 3

sample.kafka:
  topic1:
    enabled: true
    topic: localkafka-test1-topic
  topic2:
    enabled: true
    topic: localkafka-test2-topic