version: '2.1'

services:
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
  kafka:
    container_name: kafka
    image: wurstmeister/kafka:2.12-2.3.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # Topic명:Partition개수:Replica개수,Topic명:Partition개수:Replica개수, ...
      KAFKA_CREATE_TOPICS: "localkafka-test1-topic:1:1,localkafka-test2-topic:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock